server:
  port: 1210

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.140:3306/tw?autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
#    separator: $ # 定义SQL的结束符
    initialization-mode: never # 执行完毕，需要改为never，否则对已存在的表，报错（从 always 改为 never ）
    schema:
      - classpath:sql/data.sql #注意书写方式,-后面有一个空格,classpath:name.sql中间却没有空格
    data:
      - classpath:sql/schema.sql  # 注意横着写，会重复SQL而报错，data: classpath:sql/schema.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 指定存储引擎，默认是 MyIsam
    database: MYSQL
    show-sql: true # 是否在控制台打印SQL
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false # 是否启用hibernate的二级缓存
      hibernate.cache.use_query_cache: false # 启用查询缓存，不会重复打印SQL
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: none # 自动生成建表语句

