server:
  port: 1210

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.140:3306/classicmodels?autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    #    separator: $ # 定义SQL的结束符
    initialization-mode: never # 执行完毕，需要改为never，否则对已存在的表，报错（从 always 改为 never ）
    schema:
    - classpath:sql/data.sql #注意书写方式,-后面有一个空格,classpath:name.sql中间却没有空格
    data:
    - classpath:sql/schema.sql  # 注意,横着写，会重复SQL而报错，data: classpath:sql/schema.sql
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: mbDemo2.enti
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
