package tonels.mbdemo3.entity;

import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(chain = true)
public class Offices {





    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.officeCode
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String officecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.city
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.phone
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.addressLine1
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String addressline1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.addressLine2
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String addressline2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.state
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String state;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.country
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String country;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.postalCode
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String postalcode;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offices.territory
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String territory;

// todo 这个后来加的，在逆向工程基础上加的，可以返回自定义对象时，在主表的model之上，其实
    private Integer num;

    private String email;

    private Integer cNum;

    private String cState;
}