package tonels.mbdemo3.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Payments extends PaymentsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.paymentDate
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private Date paymentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.aaa
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private String aaa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.amount
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.paymentDate
     *
     * @return the value of payments.paymentDate
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    public Date getPaymentdate() {
        return paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.paymentDate
     *
     * @param paymentdate the value for payments.paymentDate
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.aaa
     *
     * @return the value of payments.aaa
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    public String getAaa() {
        return aaa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.aaa
     *
     * @param aaa the value for payments.aaa
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    public void setAaa(String aaa) {
        this.aaa = aaa == null ? null : aaa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.amount
     *
     * @return the value of payments.amount
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.amount
     *
     * @param amount the value for payments.amount
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}