package tonels.mbdemo3.dao;

import org.apache.ibatis.annotations.Mapper;
import tonels.mbdemo3.entity.Customers;
import tonels.mbdemo3.params.CustoParams;

import java.util.List;

@Mapper
public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int deleteByPrimaryKey(Integer customernumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insertSelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    Customers selectByPrimaryKey(Integer customernumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKeySelective(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKey(Customers record);

    List<Customers> selectAll();

    List<Customers> selectVo1();

    List<Customers> selectByCity(String city);

    List<Customers> selectVo2(CustoParams params);


}