package tonels.mbdemo3.dao;

import org.apache.ibatis.annotations.Mapper;
import tonels.mbdemo3.entity.Offices;

import java.util.List;

@Mapper
public interface OfficesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int deleteByPrimaryKey(String officecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insert(Offices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insertSelective(Offices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    Offices selectByPrimaryKey(String officecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKeySelective(Offices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKey(Offices record);

    List<Offices> selectByJoin();
}