package tonels.mbdemo3.dao;

import tonels.mbdemo3.entity.Orderdetails;
import tonels.mbdemo3.entity.OrderdetailsKey;

public interface OrderdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int deleteByPrimaryKey(OrderdetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insert(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insertSelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    Orderdetails selectByPrimaryKey(OrderdetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKeySelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKey(Orderdetails record);
}