package tonels.mbdemo3.dao;

import tonels.mbdemo3.entity.Payments;
import tonels.mbdemo3.entity.PaymentsKey;

public interface PaymentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int deleteByPrimaryKey(PaymentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insert(Payments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int insertSelective(Payments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    Payments selectByPrimaryKey(PaymentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKeySelective(Payments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbg.generated Tue Jul 23 15:05:27 CST 2019
     */
    int updateByPrimaryKey(Payments record);
}